language: node_js

os:
- linux
#- osx

node_js:
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'

before_install:
# update npm to latest
- npm install -g npm@latest

# show product version
- nvm --version
- node --version
- npm --version

install:
- npm install